### ISSUE TITLE
Добавить поддержку версий протокола от 1.18 и выше.

### ISSUE THREAD

**Issue by xstramec** [Titlehhhh/Minecraft-Holy-Client#13]
Добавьте поддержку версией до 1.20.1, очень нужно! Заранее спасибо

**Comment by Titlehhhh** [comment]
В ближайшее время добавлю

**Comment by whoo12232** [comment]
> yakInda ekleyececim

пожалуйста, принесите версии выше 1.18.2

**Comment by Titlehhhh** [comment]
Move to https://github.com/Titlehhhh/Minecraft-Holy-Client/discussions/59
