### ISSUE TITLE
Добавить поддержку плагинов для бот-атаки.

### ISSUE THREAD

**Issue by Kirillgfgfg** [Titlehhhh/Minecraft-Holy-Client#15]
![image](https://github.com/Titlehhhh/Minecraft-DDOS-Free/assets/138010399/4425e332-2d8a-439e-87ab-336ee3941f2f)

**Comment by rwcv** [comment]
Плагины еще не реализованы

**Comment by Titlehhhh** [comment]
В новой версии я добавлю поддержку плагинов

**Comment by Titlehhhh** [comment]
уже почти
