### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by HanSoloSnipe** [Titlehhhh/Minecraft-Holy-Client#20]
Появляется такая ошибка, и не понятно с чем это свзано.

Появляется во вкладке DDOS

Умные боты у меня работают

**Comment by Titlehhhh** [comment]
Я не смогу пофиксить эту проблему. Из-за некоторых технических проблем. Вам придется подождать, пока я не выпущу новую версию программы.

Я знаю что обновления не было очень давно. Это связано с тем что я сейчас не могу уделить достаточно времени на разработку и к тому же я ждал когда выйдет Avalonia 11 версии.

Где-то к середине августа я смогу выпустить обновление, но это не точно.
