### ISSUE TITLE
Не устанавливается 

### ISSUE THREAD

**Issue by Errarka** [Titlehhhh/Minecraft-Holy-Client#21]
Error: Произошла ошибка при попытке скачать "https://raw.githubusercontent.com/Titlehhhh/Minecraft-DDOS-Free/master/published/McHolyBot.application".

**Comment by Titlehhhh** [comment]
Я не смогу пофиксить эту проблему. Из-за некоторых технических проблем. Вам придется подождать, пока я не выпущу новую версию программы.

Я знаю что обновления не было очень давно. Это связано с тем что я сейчас не могу уделить достаточно времени на разработку и к тому же я ждал когда выйдет Avalonia 11 версии.

Где-то к середине августа я смогу выпустить обновление, но это не точно.
