### ISSUE TITLE
i wait for this client

### ISSUE THREAD

**Issue by imscruz** [Titlehhhh/Minecraft-Holy-Client#31]
### yo whatsup 
can you code really crasher on bots

think about this 

i fill server on the bot i have 15 bot on aternos server
15 use a error crash
15x1Errorcrash=Server Down
like this can you code the Crasher?

**Comment by Titlehhhh** [comment]
Do you mean disabling the server with vulnerabilities in commands, plugins, or the server core?
If so, you will most likely need to implement this yourself using plugins, which I will add shortly.

**Comment by imscruz** [comment]
> Do you mean disabling the server with vulnerabilities in commands, plugins, or the server core? If so, you will most likely need to implement this yourself using plugins, which I will add shortly.

yea i mean every bot send any lag packet and server down easyy
