### ISSUE TITLE
где можно получить более старую версию

### ISSUE THREAD

**Issue by Mlinec** [Titlehhhh/Minecraft-Holy-Client#58]
мне нужна 1.0.0.23

**Comment by portal2707070** [comment]
У меня нет версии 1.0.0.23 но у меня есть более старая версия: https://github.com/Titlehhhh/Minecraft-Holy-Client/releases/tag/Main
Скачиваешь source code потом открываешь и там папка published, извлеки её куда нибудь и потом открой файл McHolyBot.application

**Comment by portal2707070** [comment]
Я нашёл версию 1.0.0.23 в commit 9a1a1ce90448c7da66626d2768f3be1f3063592e
не уверен работает ли, https://github.com/portal2707070/files-idk/releases/tag/McHolyBot
запускать McHolyBot.exe
PS: файл на github так как не смог прикрепить к комментарию.

**Comment by portal2707070** [comment]
в файле CodingSeb.Localization.dll нашёл вирус, но похоже он не работает так как вебхук снесли
