### ISSUE TITLE
Адмэн, ты еще не забил на проект? стоит ли ждать новых обнов?

### ISSUE THREAD

**Issue by loshara2007** [Titlehhhh/Minecraft-Holy-Client#60]

**Comment by Titlehhhh** [comment]
Если я за этот август не сделаю мультиверсию, то скорее всего никогда не будет обнов

**Comment by Titlehhhh** [comment]
Мне бы дополнительные руки не помешали, но так случилось что все кто немного понимает в программировании и любит Майнкрафт, либо знают java, либо python, либо и то и то. C# мало кто знает

**Comment by Titlehhhh** [comment]
Нужно добавить поддержку всех версий, всех пакетов. Остальным я займусь

**Comment by Titlehhhh** [comment]
> > Мне бы дополнительные руки не помешали
> 
> Что именно требуется?

я добавил дискорд в readme. Если хотите стать контрибьтером, то можем в дискорде обсудить добавление мультиверсии

**Comment by loshara2007** [comment]
походу больше не будет новых версий D:

**Comment by pirateorno** [comment]
админ спасибо за обновочку. Целую руки

**Comment by Titlehhhh** [comment]
Move to https://github.com/Titlehhhh/Minecraft-Holy-Client/discussions/59
