### ISSUE TITLE
не заходит на сервера

### ISSUE THREAD

**Issue by makcnmflow** [Titlehhhh/Minecraft-Holy-Client#63]
я тупой хз че делать у меня просто не заходит на сервера вообще просто тишина
![{FC29246D-390C-4E2E-8D46-4CF2207B2994}](https://github.com/user-attachments/assets/211a9036-1131-4702-a9cb-d80e15d368fe)
![изображение](https://github.com/user-attachments/assets/34929746-2b76-4a5f-94f6-06b4d941fdfe)

**Comment by makcnmflow** [comment]
> Какая версия сервера майнкрафт и какая версия программы?

1.12.2 версия проги последния

**Comment by makcnmflow** [comment]
прокси проверенные если что давно ими пользуюсь не когда не подводили

**Comment by Titlehhhh** [comment]
К сожалению версия программы, которая последняя в релизах сыровата. Она более менее работает на версии 1.16.5, а также нужно увеличивать количество ботов, чтобы хоть сколь ни будь зашли. Попробуйте 100.

Я в данный момент работаю над обновлением, где исправил множество проблем, но ещё не все проблемы исправил. Если не получится решить ваши проблемы с программой обходными путями, которые я выше упомянул, то скорее всего вам придется подождать обновления

**Comment by makcnmflow** [comment]
> К сожалению версия программы, которая последняя в релизах сыровата. Она более менее работает на версии 1.16.5, а также нужно увеличивать количество ботов, чтобы хоть сколь ни будь зашли. Попробуйте 100.
> 
> Я в данный момент работаю над обновлением, где исправил множество проблем, но ещё не все проблемы исправил. Если не получится решить ваши проблемы с программой обходными путями, которые я выше упомянул, то скорее всего вам придется подождать обновления

пробовал все версии с 1.12.2 в плоть до 1.19
и тишина

**Comment by Titlehhhh** [comment]
Ну сервер, который вы хотите нагрузить похоже уже не работает. К тому же возможно вы использовали платные прокси(с логином и паролем), которые программа той версии не умела обрабатывать. 
![image](https://github.com/user-attachments/assets/eb45bf76-e290-43f0-942a-4a5e253472c0)

**Comment by makcnmflow** [comment]
когда он включен все так же не заходит

**Comment by makcnmflow** [comment]
по поводу прокси они бесплатные без логина и пароля

**Comment by makcnmflow** [comment]
или я что то настроил не так или я особнный

**Comment by Titlehhhh** [comment]
Можно переговорить все в дискорде, где заодно я запущу атаку с dev версии программы

**Comment by makcnmflow** [comment]
> Можно переговорить все в дискорде, где заодно я запущу атаку с dev версии программы

можно сейчас тогда зайду

**Comment by makcnmflow** [comment]
зашел

**Comment by makcnmflow** [comment]
![изображение](https://github.com/user-attachments/assets/caf4032e-d72c-4d9c-a906-06d72304f528)
![изображение](https://github.com/user-attachments/assets/91676be3-13be-4358-ae84-d2fa3ac27857)
