### ISSUE TITLE
Поддержка VDS версии программы для распределенной атаки.

### ISSUE THREAD

**Issue by GHOUL10007** [Titlehhhh/Minecraft-Holy-Client#9]
Планируете ли вы выпускать данную программу на linux ? Например чтобы запускать ботов с вдски
Думаю это было бы хорошо

**Comment by dimiprimi228** [comment]
согласен было бы полезно но без графического интерфейса просто комадная строка

**Comment by Titlehhhh** [comment]
Я сейчас отвлекся от программы на какое-то время так как учеба прижала и я еще изучаю как делать .net приложения под андроид. Как с андроидом разберусь, то выпущу версию сразу на все платформы. Но я не гарантирую, что будет работать адекватно везде, так как нет пока возможности протестить на всех платформах. 

По поводу vds версии, то скорее всего я её сделаю open source, где вы соберете её сами под конкретную платформу, но еще могу сказать, что она скорее всего будет не так часто обновлятся.
